# Generated by Django 4.2.7 on 2023-11-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('size_unit', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
                ('placement_type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticServiceProviders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('postal_code_min', models.IntegerField()),
                ('postal_code_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('details_url', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LSPTimeslots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.IntegerField()),
                ('every_other_week', models.BooleanField()),
                ('timeslot_start', models.TimeField()),
                ('timeslot_end', models.TimeField()),
                ('id_lsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.logisticserviceproviders')),
            ],
        ),
        migrations.CreateModel(
            name='LSPProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.assets')),
                ('id_lsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.logisticserviceproviders')),
                ('id_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.streams')),
            ],
        ),
    ]
