# Generated by Django 4.2.7 on 2023-11-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_alter_assets_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='lsptimeslots',
            name='timeslot_end',
            field=models.TimeField(editable=False, null=True),
        ),
    ]
