# Generated by Django 4.2.7 on 2023-11-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_customer_alter_lsptimeslots_timeslot_end'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assets',
            new_name='Asset',
        ),
        migrations.RenameModel(
            old_name='LogisticServiceProviders',
            new_name='LogisticServiceProvider',
        ),
        migrations.RenameModel(
            old_name='LSPProducts',
            new_name='LSPProduct',
        ),
        migrations.RenameModel(
            old_name='LSPTimeslots',
            new_name='LSPTimeslot',
        ),
        migrations.RenameModel(
            old_name='Streams',
            new_name='Stream',
        ),
    ]
