# Generated by Django 4.2.7 on 2023-11-29 16:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_rename_assets_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='update_at',
        ),
        migrations.AlterField(
            model_name='asset',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='logisticserviceprovider',
            name='postal_code_max',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='logisticserviceprovider',
            name='postal_code_min',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='lsptimeslot',
            name='timeslot_start',
            field=models.TimeField(null=True, validators=[django.core.validators.MinValueValidator(datetime.time(6, 0), message='Timeslot start must be between 06:00 and 20:00'), django.core.validators.MaxValueValidator(datetime.time(20, 0), message='Timeslot start must be between 06:00 and 20:00')]),
        ),
    ]
