# Generated by Django 4.2.7 on 2023-11-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_alter_asset_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='details_url',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='image_url',
        ),
    ]
