# Generated by Django 4.2.7 on 2023-11-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_remove_stream_details_url_remove_stream_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='image_url',
        ),
    ]
